# Generated by Django 4.1.5 on 2023-02-17 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_tag', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('volume', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('statut', models.BooleanField(blank=True, default=True)),
                ('imageUrl', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='essivivi_api.categories')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Eau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('volume', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('statut', models.BooleanField(blank=True, default=True)),
                ('imageUrl', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eaux', to='essivivi_api.categories')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
